# Generated by Django 4.2.4 on 2024-04-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pemberi_tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat', models.CharField(max_length=300, verbose_name='Alamat Pemberi Tugas')),
                ('desa', models.CharField(max_length=300, verbose_name='Desa Pemberi Tugas')),
                ('kecamatan', models.CharField(max_length=300, verbose_name='Kecamatan Pemberi Tugas')),
                ('kabupaten', models.CharField(max_length=300, verbose_name='Kabupaten Pemberi Tugas')),
                ('propinsi', models.CharField(max_length=300, verbose_name='Propinsi Pemberi Tugas')),
            ],
        ),
    ]
