# Generated by Django 5.0.6 on 2024-06-18 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='akun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='customerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_nama', models.CharField(max_length=100, verbose_name='Nama customer')),
            ],
        ),
        migrations.CreateModel(
            name='form_isian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isian_suratorder_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='No Surat Order')),
                ('isian_suratorder_tanggal', models.DateField(blank=True, null=True, verbose_name='Tanggal Surat Order')),
                ('isian_tujuanpenilaian', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tujuan penilaian')),
                ('isian_kantorkjpp', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kantor KJPP')),
                ('isian_pendampinginspeksi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pendamping inspeksi')),
                ('isian_spk_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='No SPK')),
                ('isian_spk_tanggal', models.DateField(blank=True, null=True, verbose_name='Tanggal SPK')),
            ],
        ),
        migrations.CreateModel(
            name='survei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survei_nosurattugas', models.CharField(blank=True, max_length=30, null=True, verbose_name='No surat tugas')),
                ('survei_tanggal', models.DateField(blank=True, null=True, verbose_name='Tanggal Survei')),
                ('survei_tahun', models.IntegerField(blank=True, null=True, verbose_name='Tahun survei')),
                ('survei_pukul', models.CharField(max_length=10, null=True, verbose_name='Waktu survei')),
                ('isian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kjpp.form_isian')),
            ],
        ),
        migrations.CreateModel(
            name='pemberi_tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pemberitugas_nama', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama pemberi tugas')),
                ('pemberitugas_alamat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Alamat pemberi tugas')),
                ('pemberitugas_desa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Desa pemberi tugas')),
                ('pemberitugas_kecamatan', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kecamatan pemberi tugas')),
                ('pemberitugas_kabupaten', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kabupaten pemberi tugas')),
                ('pemberitugas_provinsi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provinsi pemberi tugas')),
            ],
        ),
        migrations.CreateModel(
            name='testDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testField', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='debitur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debitur_namadebitur', models.CharField(blank=True, max_length=300, null=True, verbose_name='Nama debitur')),
                ('debitur_alamat', models.CharField(blank=True, max_length=300, null=True, verbose_name='Alamat debitur')),
                ('debitur_desa', models.CharField(blank=True, max_length=30, null=True, verbose_name='Desa debitur')),
                ('debitur_kecamatan', models.CharField(blank=True, max_length=30, null=True, verbose_name='Kecamatan debitur')),
                ('debitur_kabupaten', models.CharField(blank=True, max_length=30, null=True, verbose_name='Desa debitur')),
                ('debitur_propinsi', models.CharField(blank=True, max_length=30, null=True, verbose_name='Propinsi debitur')),
                ('isian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kjpp.form_isian')),
            ],
        ),
        migrations.CreateModel(
            name='objekProperti',
            fields=[
                ('survei', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='kjpp.survei')),
                ('properti_tipeproperti', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipe properti')),
                ('properti_luastanah', models.CharField(blank=True, max_length=200, null=True, verbose_name='Luas tanah')),
                ('properti_alamataset', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alamat aset')),
                ('properti_propinsi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Provinsi properti')),
                ('properti_kabupaten', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kabupaten properti')),
                ('properti_kecamatan', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kecamatan properti')),
                ('properti_kodepos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kode Pos')),
                ('properti_notelp', models.CharField(blank=True, max_length=200, null=True, verbose_name='No Telp')),
                ('properti_titikkoordinat', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titik Koordinat')),
                ('properti_pencapaianlokasiaksesjalan', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pencapaian Lokasi / Akses Jalan')),
                ('properti_lebarjalandepanproperti', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lebar jalan depan properti')),
                ('properti_kondisijalanmaterialjalan', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kondisi jalan / material jalan')),
                ('properti_penghunipersilsaatini', models.CharField(blank=True, max_length=200, null=True, verbose_name='Penghuni persil saat ini')),
                ('properti_peruntukaneksisting', models.CharField(blank=True, max_length=200, null=True, verbose_name='Peruntukan eksisting')),
                ('properti_tipebangunan', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipe bangunan')),
                ('properti_namabangunan', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nama bangunan')),
                ('properti_luasdilapangan', models.CharField(blank=True, max_length=200, null=True, verbose_name='')),
                ('properti_noimb', models.CharField(blank=True, max_length=200, null=True, verbose_name='No imb')),
                ('properti_jumlahlantai', models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='Jumlah lantai')),
                ('properti_tahunbangun', models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='Tahun bangun')),
                ('properti_tahunrenovasi', models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='Tahun renovasi')),
                ('properti_tahunpenilaian', models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='Tahun penilaian')),
                ('properti_umurekonomis', models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='Umur ekonomis')),
                ('properti_ikk', models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='IKK')),
                ('properti_ilm', models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='ILM')),
            ],
        ),
        migrations.CreateModel(
            name='detail_survei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveidate', models.DateField()),
                ('survei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kjpp.survei')),
            ],
        ),
        migrations.CreateModel(
            name='pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pegawai_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Id pegawai')),
                ('pegawai_nama', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama pegawai')),
                ('pegawai_nomappi', models.CharField(blank=True, max_length=100, null=True, verbose_name='No MAPPI pegawai')),
                ('pegawai_noregister', models.CharField(blank=True, max_length=100, null=True, verbose_name='No register pegawai')),
                ('survei', models.ManyToManyField(through='kjpp.detail_survei', to='kjpp.survei')),
            ],
        ),
        migrations.AddField(
            model_name='detail_survei',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kjpp.pegawai'),
        ),
    ]
