# Generated by Django 5.0.4 on 2024-04-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kjpp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='akun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300, verbose_name='username')),
                ('password', models.CharField(max_length=300, verbose_name='password')),
            ],
        ),
    ]
