# Generated by Django 5.0.6 on 2024-06-18 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kjpp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testDB',
        ),
    ]
