# Generated by Django 5.0.6 on 2024-05-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kjpp', '0002_akun'),
    ]

    operations = [
        migrations.CreateModel(
            name='form_isian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isian_suratorder_no', models.CharField(max_length=30, verbose_name='No Surat Order')),
                ('isian_suratorder_tanggal', models.DateField(verbose_name='Tanggal Surat Order')),
                ('isian_tujuanpenilaian', models.CharField(max_length=100, verbose_name='Tujuan penilaian')),
                ('isian_kantorkjpp', models.CharField(max_length=100, verbose_name='Kantor KJPP')),
                ('isian_pendampinginspeksi', models.CharField(max_length=100, verbose_name='Pendamping inspeksi')),
                ('isian_spk_no', models.CharField(max_length=30, verbose_name='No SPK')),
                ('isian_spk_tanggal', models.DateField(verbose_name='Tanggal SPK')),
                ('pemberitugas_nama', models.CharField(max_length=100, verbose_name='Nama pemberi tugas')),
                ('pemberitugas_alamat', models.CharField(max_length=100, verbose_name='Alamat pemberi tugas')),
                ('pemberitugas_desa', models.CharField(max_length=100, verbose_name='Desa pemberi tugas')),
                ('pemberitugas_kecamatan', models.CharField(max_length=100, verbose_name='Kecamatan pemberi tugas')),
                ('pemberitugas_kabupaten', models.CharField(max_length=100, verbose_name='Kabupaten pemberi tugas')),
                ('pemberitugas_provinsi', models.CharField(max_length=100, verbose_name='Provinsi pemberi tugas')),
                ('survei_nosurattugas', models.CharField(max_length=30, verbose_name='No surat tugas')),
                ('survei_tanggal', models.DateField(verbose_name='Tanggal Survei')),
                ('survei_tanggalterbilang', models.CharField(max_length=20, verbose_name='Tanggal terbilang survei, contoh = dua belas')),
                ('survei_bulan', models.CharField(max_length=100, verbose_name='Bulan survei, cth = Januari')),
                ('survei_tahun', models.IntegerField(verbose_name='Tahun survei')),
                ('survei_pukul', models.CharField(max_length=10, verbose_name='Waktu survei')),
                ('survei_hari', models.CharField(max_length=10, verbose_name='Hari survei')),
                ('properti_tipeproperti', models.CharField(max_length=100, verbose_name='Tipe properti')),
                ('properti_luastanah', models.IntegerField(max_length=100, verbose_name='Luas tanah')),
                ('properti_namadebitur', models.CharField(max_length=100, verbose_name='Nama debitur')),
                ('properti_alamataset', models.CharField(max_length=300, verbose_name='Alamat Aset')),
                ('properti_kelurahan', models.CharField(max_length=100, verbose_name='Kelurahan')),
                ('properti_kecamatan', models.CharField(max_length=100, verbose_name='Kecamatan')),
                ('properti_kabupaten', models.CharField(max_length=100, verbose_name='Kabupaten')),
                ('properti_provinsi', models.CharField(max_length=100, verbose_name='Provinsi')),
                ('properti_kodepos', models.CharField(max_length=10, verbose_name='Kode pos')),
                ('properti_notelp', models.CharField(max_length=15, verbose_name='No Telp')),
                ('properti_titikkoordinat', models.CharField(max_length=100, verbose_name='Titik Koordinat')),
                ('properti_pencapaianlokasiaksesjalan', models.CharField(max_length=100, verbose_name='Pencapaian lokasi / akses jalan')),
                ('properti_lebarjalandepanproperti', models.IntegerField(verbose_name='Lebar jalan depan properti')),
                ('properti_kondisijalanmaterialjalan', models.CharField(max_length=100, verbose_name='Kondisi jalan / material jalan')),
                ('properti_penghunipersilsaatini', models.CharField(max_length=100, verbose_name='Penghuni persil saat ini')),
                ('properti_peruntukaneksisting', models.CharField(max_length=100, verbose_name='Peruntukan eksisting')),
            ],
        ),
    ]
