# Generated by Django 5.0.6 on 2024-06-18 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kjpp', '0003_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='testField',
            new_name='nama_cust',
        ),
    ]
