# Generated by Django 5.0.6 on 2024-06-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kjpp', '0004_alter_akun_password_alter_akun_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_isian',
            name='properti_namabangunan',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='form_isian',
            name='status',
            field=models.CharField(default='Unknown', max_length=30, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
