# Generated by Django 5.0.6 on 2024-06-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kjpp', '0005_alter_customer_nama_cust'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='alamat_cust',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alamat customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nama_cust',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama customer'),
        ),
    ]
