# Generated by Django 5.0.6 on 2024-06-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kjpp', '0005_form_isian_properti_namabangunan_form_isian_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_isian',
            name='properti_namabangunan',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Nama Bangunan'),
        ),
    ]
