# Generated by Django 5.0.6 on 2024-06-18 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kjpp', '0006_customer_alamat_cust_alter_customer_nama_cust'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_isian',
            name='pemberitugas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kjpp.customer'),
        ),
    ]
