# Generated by Django 5.0.6 on 2024-06-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kjpp', '0007_form_isian_pemberitugas'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='desa_cust',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Desa customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='kabupaten_cust',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kabupaten customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='kecamatan_cust',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kecamatan customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='provinsi_cust',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provinsi customer'),
        ),
    ]
