# Generated by Django 5.0.6 on 2024-06-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kjpp', '0007_data_properti_remove_form_isian_pemberitugas_alamat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='survei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survei_nosurattugas', models.CharField(max_length=30, null=True, verbose_name='No surat tugas')),
                ('survei_tanggal', models.DateField(verbose_name='Tanggal Survei')),
                ('survei_tahun', models.IntegerField(verbose_name='Tahun survei')),
                ('survei_pukul', models.CharField(max_length=10, null=True, verbose_name='Waktu survei')),
            ],
        ),
        migrations.RemoveField(
            model_name='form_isian',
            name='survei_bulan',
        ),
        migrations.RemoveField(
            model_name='form_isian',
            name='survei_hari',
        ),
        migrations.RemoveField(
            model_name='form_isian',
            name='survei_nosurattugas',
        ),
        migrations.RemoveField(
            model_name='form_isian',
            name='survei_pukul',
        ),
        migrations.RemoveField(
            model_name='form_isian',
            name='survei_tahun',
        ),
        migrations.RemoveField(
            model_name='form_isian',
            name='survei_tanggal',
        ),
        migrations.RemoveField(
            model_name='form_isian',
            name='survei_tanggalterbilang',
        ),
    ]
