# Generated by Django 5.0.6 on 2024-06-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kjpp', '0008_survei_remove_form_isian_survei_bulan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='objekProperti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('properti_propinsi', models.CharField(max_length=200, verbose_name='Provinsi properti')),
                ('properti_kabupaten', models.CharField(max_length=200, verbose_name='Kabupaten properti')),
                ('properti_tipebangunan', models.CharField(max_length=200, verbose_name='Tipe bangunan')),
                ('properti_namabangunan', models.CharField(max_length=200, verbose_name='Nama bangunan')),
                ('properti_noimb', models.CharField(max_length=200, verbose_name='No imb')),
                ('properti_luasdilapangan', models.CharField(max_length=200, verbose_name='')),
            ],
        ),
        migrations.DeleteModel(
            name='data_properti',
        ),
    ]
