# Generated by Django 5.0.6 on 2024-06-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kjpp', '0009_propertydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='debitur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debitur_namadebitur', models.CharField(blank=True, max_length=300, null=True, verbose_name='Nama debitur')),
                ('debitur_alamat', models.CharField(blank=True, max_length=300, null=True, verbose_name='Alamat debitur')),
                ('debitur_desa', models.CharField(blank=True, max_length=30, null=True, verbose_name='Desa debitur')),
                ('debitur_kecamatan', models.CharField(blank=True, max_length=30, null=True, verbose_name='Kecamatan debitur')),
                ('debitur_kabupaten', models.CharField(blank=True, max_length=30, null=True, verbose_name='Desa debitur')),
                ('debitur_propinsi', models.CharField(blank=True, max_length=30, null=True, verbose_name='Propinsi debitur')),
            ],
        ),
        migrations.CreateModel(
            name='objekProperti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('properti_tipeproperti', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipe properti')),
                ('properti_luastanah', models.CharField(blank=True, max_length=200, null=True, verbose_name='Luas tanah')),
                ('properti_alamataset', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alamat aset')),
                ('properti_propinsi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Provinsi properti')),
                ('properti_kabupaten', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kabupaten properti')),
                ('properti_kecamatan', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kecamatan properti')),
                ('properti_kodepos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kode Pos')),
                ('properti_notelp', models.CharField(blank=True, max_length=200, null=True, verbose_name='No Telp')),
                ('properti_titikkoordinat', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titik Koordinat')),
                ('properti_pencapaianlokasiaksesjalan', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pencapaian Lokasi / Akses Jalan')),
                ('properti_lebarjalandepanproperti', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lebar jalan depan properti')),
                ('properti_kondisijalanmaterialjalan', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kondisi jalan / material jalan')),
                ('properti_penghunipersilsaatini', models.CharField(blank=True, max_length=200, null=True, verbose_name='Penghuni persil saat ini')),
                ('properti_peruntukaneksisting', models.CharField(blank=True, max_length=200, null=True, verbose_name='Peruntukan eksisting')),
                ('properti_tipebangunan', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipe bangunan')),
                ('properti_namabangunan', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nama bangunan')),
                ('properti_luasdilapangan', models.CharField(blank=True, max_length=200, null=True, verbose_name='')),
                ('properti_noimb', models.CharField(blank=True, max_length=200, null=True, verbose_name='No imb')),
                ('properti_jumlahlantai', models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='Jumlah lantai')),
                ('properti_tahunbangun', models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='Tahun bangun')),
                ('properti_tahunrenovasi', models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='Tahun renovasi')),
                ('properti_tahunpenilaian', models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='Tahun penilaian')),
                ('properti_umurekonomis', models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='Umur ekonomis')),
                ('properti_ikk', models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='IKK')),
                ('properti_ilm', models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='ILM')),
            ],
        ),
        migrations.CreateModel(
            name='pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pegawai_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Id pegawai')),
                ('pegawai_nama', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama pegawai')),
                ('pegawai_nomappi', models.CharField(blank=True, max_length=100, null=True, verbose_name='No MAPPI pegawai')),
                ('pegawai_noregister', models.CharField(blank=True, max_length=100, null=True, verbose_name='No register pegawai')),
            ],
        ),
    ]
