# Generated by Django 5.0.6 on 2024-06-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kjpp', '0010_objekproperti_properti_ikk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objekproperti',
            name='properti_kodepos',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='kodepos'),
        ),
    ]
