# Generated by Django 5.0.6 on 2024-06-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kjpp', '0011_objekproperti_properti_kodepos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objekproperti',
            name='properti_jumlahlantai',
            field=models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='Jumlah lantai'),
        ),
        migrations.AlterField(
            model_name='objekproperti',
            name='properti_kabupaten',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kabupaten properti'),
        ),
        migrations.AlterField(
            model_name='objekproperti',
            name='properti_luasdilapangan',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='objekproperti',
            name='properti_namabangunan',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nama bangunan'),
        ),
        migrations.AlterField(
            model_name='objekproperti',
            name='properti_noimb',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='No imb'),
        ),
        migrations.AlterField(
            model_name='objekproperti',
            name='properti_propinsi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Provinsi properti'),
        ),
        migrations.AlterField(
            model_name='objekproperti',
            name='properti_tahunbangun',
            field=models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='Tahun bangun'),
        ),
        migrations.AlterField(
            model_name='objekproperti',
            name='properti_tahunpenilaian',
            field=models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='Tahun penilaian'),
        ),
        migrations.AlterField(
            model_name='objekproperti',
            name='properti_tahunrenovasi',
            field=models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='Tahun renovasi'),
        ),
        migrations.AlterField(
            model_name='objekproperti',
            name='properti_tipebangunan',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipe bangunan'),
        ),
        migrations.AlterField(
            model_name='objekproperti',
            name='properti_umurekonomis',
            field=models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='Umur ekonomis'),
        ),
    ]
