# Generated by Django 5.0.6 on 2024-06-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kjpp', '0012_alter_objekproperti_properti_jumlahlantai_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='debitur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debitur_alamat', models.CharField(blank=True, max_length=300, null=True, verbose_name='Alamat debitur')),
                ('debitur_desa', models.CharField(blank=True, max_length=30, null=True, verbose_name='Desa debitur')),
                ('debitur_kecamatan', models.CharField(blank=True, max_length=30, null=True, verbose_name='Kecamatan debitur')),
                ('debitur_kabupaten', models.CharField(blank=True, max_length=30, null=True, verbose_name='Desa debitur')),
                ('debitur_propinsi', models.CharField(blank=True, max_length=30, null=True, verbose_name='Propinsi debitur')),
            ],
        ),
        migrations.CreateModel(
            name='pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pegawai_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Id pegawai')),
                ('pegawai_nama', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama pegawai')),
                ('pegawai_nomappi', models.CharField(blank=True, max_length=100, null=True, verbose_name='No MAPPI pegawai')),
                ('pegawai_noregister', models.CharField(blank=True, max_length=100, null=True, verbose_name='No register pegawai')),
            ],
        ),
        migrations.AlterField(
            model_name='form_isian',
            name='isian_kantorkjpp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kantor KJPP'),
        ),
        migrations.AlterField(
            model_name='form_isian',
            name='isian_pendampinginspeksi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tujuan penilaian'),
        ),
        migrations.AlterField(
            model_name='form_isian',
            name='isian_spk_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spk no'),
        ),
        migrations.AlterField(
            model_name='form_isian',
            name='isian_spk_tanggal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spk tanggal'),
        ),
        migrations.AlterField(
            model_name='form_isian',
            name='isian_suratorder_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Surat order no'),
        ),
        migrations.AlterField(
            model_name='form_isian',
            name='isian_suratorder_tanggal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Surat order tanggal'),
        ),
        migrations.AlterField(
            model_name='form_isian',
            name='isian_tujuanpenilaian',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tujuan penilaian'),
        ),
        migrations.AlterField(
            model_name='pemberi_tugas',
            name='pemberitugas_alamat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alamat pemberi tugas'),
        ),
        migrations.AlterField(
            model_name='pemberi_tugas',
            name='pemberitugas_desa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Desa pemberi tugas'),
        ),
        migrations.AlterField(
            model_name='pemberi_tugas',
            name='pemberitugas_kabupaten',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kabupaten pemberi tugas'),
        ),
        migrations.AlterField(
            model_name='pemberi_tugas',
            name='pemberitugas_kecamatan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kecamatan pemberi tugas'),
        ),
        migrations.AlterField(
            model_name='pemberi_tugas',
            name='pemberitugas_nama',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama pemberi tugas'),
        ),
        migrations.AlterField(
            model_name='pemberi_tugas',
            name='pemberitugas_provinsi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provinsi pemberi tugas'),
        ),
    ]
