# Generated by Django 5.0.6 on 2024-06-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kjpp', '0013_debitur_pegawai_alter_form_isian_isian_kantorkjpp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objekproperti',
            name='properti_alamataset',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alamat aset'),
        ),
        migrations.AddField(
            model_name='objekproperti',
            name='properti_kecamatan',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kecamatan properti'),
        ),
        migrations.AddField(
            model_name='objekproperti',
            name='properti_kondisijalanmaterialjalan',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kondisi jalan / material jalan'),
        ),
        migrations.AddField(
            model_name='objekproperti',
            name='properti_lebarjalandepanproperti',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lebar jalan depan properti'),
        ),
        migrations.AddField(
            model_name='objekproperti',
            name='properti_luastanah',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Luas tanah'),
        ),
        migrations.AddField(
            model_name='objekproperti',
            name='properti_notelp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='No Telp'),
        ),
        migrations.AddField(
            model_name='objekproperti',
            name='properti_pencapaianlokasiaksesjalan',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pencapaian Lokasi / Akses Jalan'),
        ),
        migrations.AddField(
            model_name='objekproperti',
            name='properti_penghunipersilsaatini',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Penghuni persil saat ini'),
        ),
        migrations.AddField(
            model_name='objekproperti',
            name='properti_peruntukaneksisting',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Peruntukan eksisting'),
        ),
        migrations.AddField(
            model_name='objekproperti',
            name='properti_tipeproperti',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipe properti'),
        ),
        migrations.AddField(
            model_name='objekproperti',
            name='properti_titikkoordinat',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titik Koordinat'),
        ),
        migrations.AlterField(
            model_name='objekproperti',
            name='properti_kodepos',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kode Pos'),
        ),
    ]
