# Generated by Django 5.0.6 on 2024-06-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kjpp', '0014_objekproperti_properti_alamataset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='survei_tahun',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tahun survei'),
        ),
        migrations.AlterField(
            model_name='survei',
            name='survei_tanggal',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Survei'),
        ),
    ]
