# Generated by Django 5.0.6 on 2024-06-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kjpp', '0015_alter_survei_survei_tahun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitur',
            name='debitur_namadebitur',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Nama debitur'),
        ),
    ]
